// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdhVrzncbiZTOAU-FnJYgVf0nAMBQP7w',
    appId: '1:803533531502:web:1bebf48eb09f2d2e9ff97f',
    messagingSenderId: '803533531502',
    projectId: 'watchlistapp-fe686',
    authDomain: 'watchlistapp-fe686.firebaseapp.com',
    storageBucket: 'watchlistapp-fe686.firebasestorage.app',
    measurementId: 'G-76HK8NJTSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxg_F4jnSElTkska4BBQzbgSDTs-jqVNQ',
    appId: '1:803533531502:android:90efc2cbc7a787429ff97f',
    messagingSenderId: '803533531502',
    projectId: 'watchlistapp-fe686',
    storageBucket: 'watchlistapp-fe686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3KS1J1DkQovNtl8JEPgiApimYtNSDGdI',
    appId: '1:803533531502:ios:c9b37263ec4502719ff97f',
    messagingSenderId: '803533531502',
    projectId: 'watchlistapp-fe686',
    storageBucket: 'watchlistapp-fe686.firebasestorage.app',
    iosBundleId: 'com.example.watchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3KS1J1DkQovNtl8JEPgiApimYtNSDGdI',
    appId: '1:803533531502:ios:c9b37263ec4502719ff97f',
    messagingSenderId: '803533531502',
    projectId: 'watchlistapp-fe686',
    storageBucket: 'watchlistapp-fe686.firebasestorage.app',
    iosBundleId: 'com.example.watchlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDdhVrzncbiZTOAU-FnJYgVf0nAMBQP7w',
    appId: '1:803533531502:web:be43a51c1b0673659ff97f',
    messagingSenderId: '803533531502',
    projectId: 'watchlistapp-fe686',
    authDomain: 'watchlistapp-fe686.firebaseapp.com',
    storageBucket: 'watchlistapp-fe686.firebasestorage.app',
    measurementId: 'G-L3PX994SS6',
  );

}